ContentCompilers: 
- CompilerType: 'NumericIncrementer'
  Description: '   PK_Quesiton    '
  Params: '  /p:From=70270  /p:To=70914 /p:Pattern=7[0-3]\d\d\d'  
- CompilerType: 'NumericIncrementer'
  Description: 'PK_FormPage'
  Params: '  /p:From=4930  /p:To=4955  /p:Pattern=493\d'
- CompilerType: 'NumericIncrementer'
  Description: 'PK_QuestionGroup'
  Params: '  /p:From=5430   /p:To=5455  /p:Pattern=543\d'  
- CompilerType: 'RegexReplacer'
  Params: ' /p:Source={ "Q1":"Q2", "175--PK_R":"179--PK_R" } '    
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: ' /p:Source={  "Q1":"Q2", "7.66":"7.67", "_5_":"_3_"  } ' 
Compilations:     
- FileFilter: '*_5_DBUpdate7.66_MFA*'
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Archive\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\'  
- FileFilter: '*_Q1_*'
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\MFA\2025\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\MFA\2025\'  