ContentCompilers: 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=58800  /p:To=60300 /p:Pattern=[5-6][0-9]\d\d\d' 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=5010   /p:To=5030  /p:Pattern=50\d\d' 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=4509   /p:To=4530  /p:Pattern=45\d\d'  
- CompilerType: 'RegexReplacer'
  Params: ' /p:Source={  "Q1":"Q2", "148--PK_R":"149--PK_R" } '    
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: ' /p:Source={ "Q1":"Q2", "7.59":"7.60", "_0_":"_FOO_" } ' 
Compilations:     
- FileFilter: '*_0_DBUpdate7.59_CIO_Q1_2024.sql'
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\'
  Dest: 'c:\temp\'  
- FileFilter: '*_Q1_*'
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2024\'
  Dest: 'c:\temp\'  