ContentCompilers:  
- CompilerType: 'NumericIncrementer'
  Description: '   PK_Quesiton    '
  Params: '  /p:From=70421  /p:To=70930 /p:Pattern=7[0-1]\d\d\d'  
- CompilerType: 'NumericIncrementer'
  Description: '   PK_FormPage    '
  Params: '  /p:PrevSeed=4935   /p:NextSeed=4960  /p:Pattern=49\d\d' 
- CompilerType: 'NumericIncrementer'
  Description: '   PK_QuestionGroup    '
  Params: '  /p:PrevSeed=5435   /p:NextSeed=5460  /p:Pattern=54\d\d'   
- CompilerType: 'RegexReplacer'
  Params: '  /p:Source={  "Q2":"Q3", "178--PK_R":"182--PK_R" } '  
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: '  /p:Source={ "Q2":"Q3", "7.67":"7.69" } ' 
Compilations:     
- FileFilter: '*_3_DBUpdate7.67_CIO_Q2_2025.sql' 
  Source: 'C:\temp\CyberScopeBranch_Release\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\'  
- FileFilter: '*_Q2_*' 
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2025\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2025\'
- FileFilter: '*frmVal_2025Q2CIO.sql*' 
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Sprocs\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Sprocs\'
 