ContentCompilers: 
- CompilerType: 'KeyValReplacer'
  Params: ' /p:Source={  "{Dependancy}":""  } ' 
- CompilerType: 'RegexReplacer'
  Params: ' /p:Source={  "QuestionNumber=.*\{idt\}":"QuestionNumber={Idtext}" } ' 
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: ' /p:Source={  "~":"" } ' 
Compilations: 
- FileFilter: '*aspx'
  Source: 'C:\Users\Tim\source\repos\Py\snippets\CodeGenerators\snippets\aspx\'
  Dest: 'C:\Users\Tim\source\repos\Py\snippets\CodeGenerators\snippets\aspx\'  