ContentCompilers: 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=53000  /p:To=63800 /p:Pattern=53\d\d\d' 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=4290   /p:To=4620  /p:Pattern=4[2-3]\d\d' 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=4450   /p:To=5120  /p:Pattern=44[5-6]\d'  
- CompilerType: 'RegexReplacer'
  Params: ' /p:Source={ "2023":"2024", "136--PK_R":"162--PK_R" } '  
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: ' /p:Source={ "2023":"2024",  "7.53":"7.62",  "_5_":"_3_" } ' 
Compilations:     
- FileFilter: '*_5_DBUpdate7.53_IG.sql'
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Archive\'
  Dest: 'D:\temp\IG' 
- FileFilter: '*frmval_IG_2023.sql'
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Sprocs\'
  Dest: 'D:\temp\IG' 
- FileFilter: '*_IG_*'
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2023\'
  Dest: 'D:\temp\IG'
 