ContentCompilers: 
- CompilerType: 'NumericIncrementer'
  Description: '   PK_Quesiton    '
  Params: '  /p:From=63500  /p:To=64800 /p:Pattern=635\d\d'  
- CompilerType: 'NumericIncrementer'
  Description: 'PK_FormPage'
  Params: '  /p:From=4610   /p:To=4660  /p:Pattern=46[1-2]\d'
- CompilerType: 'NumericIncrementer'
  Description: 'PK_QuestionGroup'
  Params: '  /p:From=5110   /p:To=5150  /p:Pattern=51[1-2]\d'  
- CompilerType: 'RegexReplacer'
  Params: ' /p:Source={ "Q3":"Q4", "161--PK_R":"164--PK_R" } '    
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: ' /p:Source={  "Q3":"Q4", "7.62":"7.63", "_2_":"_1_" } ' 
Compilations:     
- FileFilter: '*_2_DBUpdate7.62_MFA.sql'
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Archive\'
  Dest: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\'  
- FileFilter: '*_Q3_*'
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\MFA\2024\'
  Dest: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\MFA\2024\'  