ContentCompilers: 
- CompilerType: 'NumericIncrementer'
  Description: '   YEAR    '
  Params: '  /p:PrevSeed=2024  /p:NextSeed=2025 /p:Pattern=2024' 
- CompilerType: 'NumericIncrementer'
  Description: '   PK_Quesiton    '
  Params: '  /p:From=64800  /p:To=70270 /p:Pattern=6[4-9]\d\d\d'  
- CompilerType: 'NumericIncrementer'
  Description: 'PK_FormPage'
  Params: '  /p:From=4660  /p:To=4930  /p:Pattern=466\d'
- CompilerType: 'NumericIncrementer'
  Description: 'PK_QuestionGroup'
  Params: '  /p:From=5150   /p:To=5430  /p:Pattern=515\d'  
- CompilerType: 'RegexReplacer'
  Params: ' /p:Source={ "Q4":"Q1", "165--PK_R":"175--PK_R" } '    
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: ' /p:Source={  "Q4":"Q1", "7.63":"7.66", "_1_":"_5_", "2024":"2025" } ' 
Compilations:     
- FileFilter: '*_Q4_*'
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\MFA\2024\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\MFA\2025\'  