ContentCompilers: 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=55000  /p:To=58800 /p:Pattern=5[0-9]\d\d\d' 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=4500   /p:To=5010  /p:Pattern=45\d\d' 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=4310   /p:To=4510  /p:Pattern=43\d\d'  
- CompilerType: 'RegexReplacer'
  Params: ' /p:Source={ "2023":"2024", "Q4":"Q1", "140--PK_R":"148--PK_R" } '    
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: ' /p:Source={ "2023":"2024", "Q4":"Q1", "7.56":"7.59", "_2_":"_0_" } ' 
Compilations:     
- FileFilter: '*_2_DBUpdate7.56_CIO_Q4_2023.sql'
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Archive\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\'  
- FileFilter: '*_Q4_*'
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2023\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2024\'
 