ContentCompilers:  
- CompilerType: 'NumericReplacer'
  Description: '   pk_question    ' 
  Skip: 'false'
  Params: '  /p:Source=~\Tasks\cio-keys.json'  
- CompilerType: 'NumericIncrementer'
  Description: '   PK_FormPage    '
  Params: '  /p:PrevSeed=4910   /p:NextSeed=4935  /p:Pattern=49\d\d' 
- CompilerType: 'NumericIncrementer'
  Description: '   PK_QuestionGroup    '
  Params: '  /p:PrevSeed=5410   /p:NextSeed=5435  /p:Pattern=54\d\d'   
- CompilerType: 'RegexReplacer'
  Params: '  /p:Source={  "Q1":"Q2", "174--PK_R":"178--PK_R" } '  
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: '  /p:Source={ "Q1":"Q2", "7.66":"7.67" } ' 
Compilations:     
- FileFilter: '*CIO_Q1_2025.sql' 
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Archive\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\'  
- FileFilter: '*_Q1_*' 
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2025\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2025\'
- FileFilter: '*frmVal_2025Q1CIO.sql*' 
  Source: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Sprocs\'
  Dest: 'C:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Sprocs\'
 