ContentCompilers: 
- CompilerType: 'NumericIncrementer'
  Description: '   PK_Quesiton    '
  Params: '  /p:PrevSeed=61798  /p:NextSeed=64810 /p:Pattern=6[1-4]\d\d\d' 
- CompilerType: 'NumericIncrementer'
  Description: '   PK_FormPage    '
  Params: '  /p:PrevSeed=4580   /p:NextSeed=4665  /p:Pattern=45[8-9]\d' 
- CompilerType: 'NumericIncrementer'
  Description: '   PK_QuestionGroup    '
  Params: '  /p:PrevSeed=5081   /p:NextSeed=5155  /p:Pattern=50[8-9]\d'  
- CompilerType: 'RegexReplacer'
  Params: '  /p:Source={  "Q3":"Q4", "160--PK_R":"166--PK_R" } '  
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: '  /p:Source={  "Q3":"Q4", "7.62":"7.63", "_0_":"_3_" } ' 
Compilations:     
- FileFilter: '*_0_DBUpdate7.62_CIO_Q3_2024.sql' 
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Archive\'
  Dest: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\'  
- FileFilter: '*_Q3_*' 
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2024\'
  Dest: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2024\'
- FileFilter: '*frmVal_2024Q3CIO.sql*' 
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Sprocs\'
  Dest: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Sprocs\'
 