ContentCompilers: 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=53000  /p:To=61800 /p:Pattern=6[0-3]\d\d\d' 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=4290   /p:To=4580  /p:Pattern=4[2-3]\d\d' 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=4450   /p:To=5080  /p:Pattern=44[5-6]\d'  
- CompilerType: 'RegexReplacer'
  Params: ' /p:Source={ "2023":"2024", "Q2":"Q3", "136--PK_R":"161--PK_R" } '    
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: ' /p:Source={ "2023":"2024", "Q2":"Q3", "7.53":"7.62",  "_5_":"_1_" } ' 
Compilations:     
- FileFilter: '*_5_DBUpdate7.53_IG.sql'
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Archive\'
  Dest: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\'  
- FileFilter: '*_IG_*'
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2023\'
  Dest: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2024\'
 