ContentCompilers: 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=60300  /p:To=61800 /p:Pattern=6[0-3]\d\d\d' 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=4550   /p:To=4580  /p:Pattern=45[5-6]\d' 
- CompilerType: 'NumericIncrementer'
  Params: '  /p:From=5050   /p:To=5080  /p:Pattern=50[5-6]\d'  
- CompilerType: 'RegexReplacer'
  Params: ' /p:Source={  "Q2":"Q3", "150--PK_R":"160--PK_R" } '    
FilenameCompilers:  
- CompilerType: 'KeyValReplacer'
  Params: ' /p:Source={  "Q2":"Q3", "7.60":"7.62", "_2_":"_3_" } ' 
Compilations:     
- FileFilter: '*_0_DBUpdate7.60_CIO_Q2_2024.sql'
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Archive\'
  Dest: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\'  
- FileFilter: '*_Q2_*'
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2024\'
  Dest: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope\FismaForms\2024\'
- FileFilter: '*frmVal_2024Q2CIO.sql*'
  Source: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Sprocs\'
  Dest: 'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\database\Sprocs\'
 